[server]
#hostname = "publisher.wso2.com"
server_role = "api-publisher-deprecated"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
hostname = "apim.mysql"
name = "apimgt_db"
port = "3306"
username = "apimuser"
password = "apimuser"

[database.shared_db]
type = "mysql"
hostname = "shared_db.mysql"
name = "shared_db"
port = "3306"
username = "shareduser"
password = "shareduser"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name= "Default"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url= "https://gw.mgt.wso2.com:443/services/"
username= "${admin.username}"
password= "${admin.password}"
http_endpoint = "http://api.gw.wso2.com:8280/"
https_endpoint = "https://api.gw.wso2.com:8243/"

# key manager implementation
[apim.key_manager]
service_url = "https://km.wso2.com:443/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

# Traffic Manager configurations
[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
service_url = "https://tm.wso2.com:443/services/"
throttle_decision_endpoints = ["tcp://tm1.local:5672","tcp://tm2.local:5672"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm1.local:9611"]
traffic_manager_auth_urls=["ssl://tm1.local:9711"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://tm2.local:9611"]
traffic_manager_auth_urls=["ssl://tm2.local:9711"]

[apim.cache.scopes]
enable = true

[apim.cache.publisher_roles] #check the usage and move to dev role
enable = true

[apim.devportal]
url = "https://devportal.wso2.com:443/devportal"

[apim.workflow]
enable = false
service_url = "https://localhost:9445/bpmn"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
callback_endpoint = "https://localhost:9443/api/am/publisher/v0.16/workflows/update-workflow-status"
token_endpoint = "https://localhost:8243/token"
client_registration_endpoint = "https://localhost:9443/client-registration/v0.17/register"
client_registration_username = "$ref{super_admin.username}"
client_registration_password = "$ref{super_admin.password}"